language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
deploy:
  before_script: yarn build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: out
  on:
    branch: master
